### ISSUE TITLE
Only one column in resulting file after  ExcelGen.addSheetFromQuery or ExcelGen.addTable (ref_cursor)

### ISSUE THREAD

**Issue by Apeldop** [mbleron/ExcelGen#67] opened 2024-12-03 15:00 UTC
![image](https://github.com/user-attachments/assets/71884e8e-227e-4d86-b8f9-3d77dcdbc15c)

Hello! Thank you very much for your work.

I'm trying to figure out how to work with the package.

I'm trying to create the simplest Excel with a sheet from a query (I took an example from yours, but substituted my query)

declare
ctxId ExcelGen.ctxHandle;
sheet1 ExcelGen.sheetHandle;
begin
ctxId := ExcelGen.createContext(ExcelGen.FILE_XLSX);
sheet1 := ExcelGen.addSheetFromQuery(ctxId, 'sheet1', 'select person_id p1, full_name p2 from per_all_people_f pap where rownum<5');
ExcelGen.createFile(ctxId, 'TEST_DIR', 'my_file.xlsx');
ExcelGen.closeContext(ctxId);
end;

But the resulting file contains only one column from the query (person_id p1)

The same thing happens if you add a table via sys_refcursor and ExcelGen.addTable(ctx, sheet1, Ref_c);

What could be the problem?

**Comment by mbleron** [comment] 2024-12-03 17:37
Hi,
No idea what could be wrong, at the moment.
Could you please post the exact script you're running? In the example, the sheet name is 'sheet1' but in the screenshot it appears as 'test'...

**Comment by Apeldop** [comment] 2024-12-04 06:58
Hi! Thanks for your reply.

So, I'm doing a test:
I install ExcelGen 4.0 on a clean clone of the OEBS 
select * from v$version;
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
PL/SQL Release 11.2.0.4.0 - Production
"CORE 11.2.0.4.0 Production"
TNS for Linux: Version 11.2.0.4.0 - Production

NLSRTL Version 11.2.0.4.0 - Production

Then I run the script to check


declare
  sheet1  ExcelGen.sheetHandle;
  sheet2  ExcelGen.sheetHandle;
  table1  ExcelGen.tableHandle;
  ctx     ExcelGen.ctxHandle;
  rc      sys_refcursor;
begin
  ExcelGen.setDebug(TRUE);
  ctx := ExcelGen.createContext(ExcelGen.FILE_XLSX);
   
  sheet1 := ExcelGen.addSheet(ctx, 'test');

  open rc for
  select 'sheet 1 col 1' p1, 'sheet 1 col 2' p2 from dual  union all 
  select 'sheet 1 col 1.1' , 'sheet 1 col 2.2'  from dual ;

  table1 := ExcelGen.addTable(ctx, sheet1, rc);
  ExcelGen.setColumnProperties(ctx, sheet1, 1, p_width => 10);
  ExcelGen.setColumnProperties(ctx, sheet1, 2, p_width => 50);
  
  sheet2 := ExcelGen.addSheetFromQuery(ctx, 'sheet2', ' select ''sheet 2 col 1'' p1, ''sheet 2 col 2'' p2 from dual  union all 
  select ''sheet 2 col 1.1'' , ''sheet 2 col 2.2''  from dual');
  ExcelGen.setHeader(ctx, sheet2, p_frozen => true);
  
  ExcelGen.setColumnProperties(ctx, sheet2, 1, p_width => 30);
  ExcelGen.setColumnProperties(ctx, sheet2, 2, p_width => 15);
  
  ExcelGen.createFile(ctx, 'XXMCDRU_HR087_OUTFILE_DIR', 'test.xlsx');
  ExcelGen.closeContext(ctx);

end;



I attach the resulting file - the same thing, only one column is generated
I also attach the output of the debug

[debug_output.txt](https://github.com/user-attachments/files/18003799/debug_output.txt)
[test.xlsx](https://github.com/user-attachments/files/18003800/test.xlsx)

**Comment by mbleron** [comment] 2024-12-04 08:18
Thanks for the test case.
I don't reproduce the issue on 12.1.0.2, I'll try to grab a 11.2 to check.

**Comment by mbleron** [comment] 2024-12-04 21:05
Just reproduced on 11.2.0.4.
It's a PL/SQL behaviour that has changed in later versions apparently.
Basically, it affects the apparent mutability of IN parameters, which are passed by reference (as documented), and normally not mutable.
But actually, if we pass a (global) variable from the parent scope to a subroutine, and modify that variable from within the subroutine using its original name, the value of the formal parameter also changes, which makes perfect sense since it's a pointer.

In the present case, that side-effect arises in my implementation of a doubly-linked list I use to store the column list:
https://github.com/mbleron/ExcelGen/blob/2d32ded190de05aa34ac6ff3a137dc79b38aadb6/plsql/ExcelGen.pkb#L859-L866
`insertAfter` modifies `t.last` internally which affects the value of the formal parameter and eventually the first column never gets a link to the second one.
The `t.last+0` thingy is there to force the value to be passed by copy, and that works on 12.1+, but on 11.2 the PL/SQL compiler just seems to optimize that away, as confirmed by setting PLSQL_OPTIMIZE_LEVEL = 0 which make it work, but highly not recommended.

Anyway, this is a easy fix I should have done in the first place.
I'll be able to publish the correction by the end of the week.

**Comment by mbleron** [comment] 2024-12-07 14:23
Fixed in v4.2.1.

**Closed by mbleron** 2024-12-07 14:23 UTC
Labels: bug
